### ISSUE TITLE
Cannot create database using Dapper and database name passed in as @ variable, why?

### ISSUE THREAD

**Issue by marekpetak** [StackExchange/Dapper#1136]
I have a code to create database with dapper:

    public static bool CreateDatabase(string connectionString, string databaseName)
	{
		const string DATABASE_CREATE_QUERY = "CREATE DATABASE (@databaseName)";

		using (var connection = new SqlConnection(connectionString))
		{
			var affectedRows = connection.Execute(DATABASE_CREATE_QUERY, new { databaseName });

			return affectedRows > 0 ? true : false;
		}
	}
	
	CreateDatabase("Server=10.10.10.10;User ID=user;Password=password;MultipleActiveResultSets=true;", "TEST_DB");
	
Every time I run this method, I get an error: 

> Incorrect syntax near '('.

With trace:

    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
    at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in E:\GitHub\Dapper\Dapper\SqlMapper.cs:line 2827
    at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in E:\GitHub\Dapper\Dapper\SqlMapper.cs:line 570
    at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in E:\GitHub\Dapper\Dapper\SqlMapper.cs:line 443
    at DbCreator.DbUtils.CreateDatabase(String connectionString, String databaseName) in E:\src_projects\DbCreator\DbUtils.cs:line 48
    at DbCreator.***.Run(String connectionString) in E:\src_projects\DbCreator\***.cs:line 23
    
If I set the query the ugly way

    const string DATABASE_CREATE_QUERY = $"CREATE DATABASE {databaseName}";
	
and run

	connection.Execute(DATABASE_CREATE_QUERY);

it all works fine.

If I don't use the brackets () in the QUERY

    const string DATABASE_CREATE_QUERY = "CREATE DATABASE @databaseName";

I get an error: 

> Incorrect syntax near '@databaseName'

I have also tried methods ExecuteScalar, Query, but with the same result.

Any ideas why this wont work the Dapper way?

aslo asked on StackOverflow https://stackoverflow.com/questions/52648188/cannot-create-database-using-dapper-and-database-name-passed-in-as-variable-w

**Comment by sgoodgrove** [comment]
As per StackOverflow it is directly reliant on SQL Server behaviour and the database name cannot be parameterised.

https://stackoverflow.com/a/52648645/356386

**Comment by jhaygood86** [comment]
Use =databaseName instead. That gets replaced by Dapper before sending to SQL

**Comment by fwd079** [comment]
> Use =databaseName instead. That gets replaced by Dapper before sending to SQL

This code still gives error in SQL Server:

```csharp
var connectionString = @"Server=localhost\SQLEXPRESS;Database=MyTEST;Integrated Security=true";
var sqlConnectionStringBuilder = new SqlConnectionStringBuilder(connectionString);
var databaseName = sqlConnectionStringBuilder.InitialCatalog.Dump("Database Name");

// Change name to master to check.
sqlConnectionStringBuilder.InitialCatalog = "master";

using (var connection = new SqlConnection(sqlConnectionStringBuilder.ConnectionString))
{
 connection.Open();
 var result = connection.ExecuteScalar<int?>(@"SELECT DB_ID(@databaseName);", new { databaseName }).Dump("DB_ID");
 
 if (!result.HasValue)
 {
  // Create Database. 
  using (var transaction = connection.BeginTransaction())
  {
   connection.Execute(@"CREATE DATABASE =databaseName", new { databaseName }, transaction);
   transaction.Commit();
  }
 }
 
 if (connection.State != ConnectionState.Closed)
 { 
  connection.Close();
 }
}
```

Error: `SqlException: Incorrect syntax near '='.`

SQL server version information:
```
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64) 
	Aug 22 2017 17:04:49 
	Copyright (C) 2017 Microsoft Corporation
	Express Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 17763: )
```

Regards.

**Comment by NickCraver** [comment]
As with the earlier issues, the database name cannot be a parameter. It's not a Dapper limitation, but a SQL Server thing. You'll need to actually put the database name into the text being executed, e.g.
```c#
connection.Execute($"CREATE DATABASE {databaseName}", transaction);
```

Note: this is using C# interpolated strings for brevity of explaining the example. I do not recommend using them in general for SQL-related things as it confuses with _actual_ parameterized strings.

**Comment by NickCraver** [comment]
Closing this out to cleanup - answered above!
