### ISSUE TITLE
Get System.NullReferenceException when query completed

### ISSUE THREAD

**Issue by seanmars** [StackExchange/Dapper#1159]
I use Dapper on .NET Core 2.1, when i use the `Dapper.Rainbow` to insert some data, i got some error message below:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Dapper.Database`1.Dispose() in C:\projects\dapper\Dapper.Rainbow\Database.cs:line 469
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesFeature.Dispose()
   at Microsoft.AspNetCore.Http.HttpResponse.<>c.<.cctor>b__30_1(Object disposable)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FireOnCompletedAwaited(Stack`1 onCompleted)
```

**Comment by seanmars** [comment]
I found the problem.
I inject the `Database<T>` to my repository,  there is no need to inject it.
