### ISSUE TITLE
Dapper and DotConnect are not working

### ISSUE THREAD

**Issue by dramirezgmd** [StackExchange/Dapper#1232]
When I try to insert a new row using  the `Execute` command, I get the following error:

```
column "name" does not exist
   at Devart.Data.PostgreSql.e.f(r A_0)
   at Devart.Data.PostgreSql.r.n()
   at Devart.Data.PostgreSql.PgSqlCommand.InternalPrepare(Boolean implicitPrepare, Int32 startRecord, Int32 maxRecords)
   at Devart.Common.DbCommandBase.ExecuteDbDataReader(CommandBehavior behavior, Boolean nonQuery)
   at Devart.Common.DbCommandBase.ExecuteDbDataReader(CommandBehavior behavior)
   at Devart.Common.DbCommandBase.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
```

My object definition is this:

```
  public class Label
  {
        public string Name { get; set; }
        public string Description { get; set; }
  }
```

My execute command is this:

```
string command = @"INSERT INTO label (name, description) VALUES (@name, @description)";

  using (IDbConnection connection = new PgSqlConnection(connectionString))
  {
        connection.Open();
        Label label = new Label
         {
               Name = "DapperTest",
               Description = "test",
         };
        connection.Execute(command, label, commandType: CommandType.Text);
  }
```

The code above works with `Npgsql`.

**Comment by alexandretperez** [comment]
The problem is on parameters.

I'm also facing the same problem using Devart.Data.MySql.

e.g:

```mysql 
db.Query("SELECT id, name FROM table WHERE id > @id", new { id = 45 })
```
The code above does **not** work!

But...
```mysql 
db.Query("SELECT id, name FROM table WHERE id > 45")
```

Works!

I'm not sure whether the problem is on Dapper or in dotConnect.

**Comment by mgravell** [comment]
Is this he same as #1296 (please see discussion there)?

**Comment by NickCraver** [comment]
Closing as duplicate of #1296
