### ISSUE TITLE
Confusing error message when setter is missing

### ISSUE THREAD

**Issue by sklivvz** [StackExchange/Dapper#1237]
If you have a property in your dao like so

```
 int Prop { get; }

````

and you try to do a `Query` that maps to it, an exception is raised. This is fine.
The exception which is raised though is confusing:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: meth
   at System.Reflection.Emit.DynamicILGenerator.Emit(OpCode opcode, MethodInfo meth)
   at Dapper.SqlMapper.GetTypeDeserializerImpl(Type type, IDataReader reader, Int32 startBound, Int32 length, Boolean returnNullIfFirstMissing) in SqlMapper.cs:line 3299
   at Dapper.SqlMapper.TypeDeserializerCache.GetReader(IDataReader reader, Int32 startBound, Int32 length, Boolean returnNullIfFirstMissing) in SqlMapper.TypeDeserializerCache.cs:line 153
   at Dapper.SqlMapper.TypeDeserializerCache.GetReader(Type type, IDataReader reader, Int32 startBound, Int32 length, Boolean returnNullIfFirstMissing) in SqlMapper.TypeDeserializerCache.cs:line 50
   at Dapper.SqlMapper.GetDeserializer(Type type, IDataReader reader, Int32 startBound, Int32 length, Boolean returnNullIfFirstMissing) in SqlMapper.cs:line 1787
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in SqlMapper.Async.cs:line 427
```

Can we have something more useful?

**Comment by NickCraver** [comment]
Do you have a full example? We support get-only properties behind the scenes, so it's probably something else in play here.

**Comment by sklivvz** [comment]
Here's a minimal example for linqpad (you'll need to add some packages). Everything works if I use `Query` and not `QueryAsync`.

```
async Task Main()
{
	SqlMapper.SetTypeMap(typeof(Foo), new ColumnAttributeTypeMapper<Foo>());
	
	using (var connection = new NpgsqlConnection("Host=127.0.0.1;Port=5432;Database=postgres;User Id=postgres;Password=example;"))
	{
		await connection.QueryAsync<Foo>(@"SELECT 1 AS project_id");
	}
}

public class Foo
{
	[Column("project_id")]
	public int ProjectId { get; }
}

public class ColumnAttributeTypeMapper<TEntity> : SqlMapper.ITypeMap
{
	private readonly DefaultTypeMap _baseTypeMap = new DefaultTypeMap(typeof(TEntity));
	private readonly IDictionary<string, PropertyInfo> _propertyMap = new Dictionary<string, PropertyInfo>();

	public ColumnAttributeTypeMapper()
	{
		var properties = typeof(TEntity).GetProperties(BindingFlags.Public | BindingFlags.Instance);
		foreach (var property in properties)
			foreach (var attribute in property.GetCustomAttributes<ColumnAttribute>())
				_propertyMap[attribute.Name] = property;
	}

	public ConstructorInfo FindConstructor(string[] names, Type[] types)
	{
		return _baseTypeMap.FindConstructor(names, types);
	}

	public ConstructorInfo FindExplicitConstructor()
	{
		return _baseTypeMap.FindExplicitConstructor();
	}

	public SqlMapper.IMemberMap GetConstructorParameter(ConstructorInfo constructor, string columnName)
	{
		return _baseTypeMap.GetConstructorParameter(constructor, columnName);
	}

	public SqlMapper.IMemberMap GetMember(string columnName)
	{
		return _propertyMap.TryGetValue(columnName, out var mappedProperty)
			? new DapperProperty(columnName, mappedProperty)
			: _baseTypeMap.GetMember(columnName);
	}

	private class DapperProperty : SqlMapper.IMemberMap
	{
		public string ColumnName { get; }
		public Type MemberType { get; }
		public PropertyInfo Property { get; }
		public FieldInfo Field => null;
		public ParameterInfo Parameter => null;

		public DapperProperty(string columnName, PropertyInfo property)
		{
			ColumnName = columnName;
			MemberType = property.PropertyType;
			Property = property;
		}
	}
}
```
