### ISSUE TITLE
SqlException raised : System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','

### ISSUE THREAD

**Issue by Fniz** [StackExchange/Dapper#1391]
Hi everyone, 

I have an issue regarding a very simple query:

`await _connection
	.QueryAsync<LegalEntityInformation>(@"
		SELECT [LE],[BU],[LegalEntity],[Email],[LastInvoiceNumber]
		FROM [EInvoicing].[dbo].[vwLegalEntities]")
	.ConfigureAwait(false);`

As you can see in the title, the exception seens not match with the "real" error : 
`System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.`

If I write the same query but in a synchronous way, it works normally
` _connection.Query<LegalEntityInformation>(@"
						SELECT [LE],[BU],[LegalEntity],[Email],[LastInvoiceNumber]
						FROM [EInvoicing].[dbo].[vwLegalEntities]")`

Here is the stacktrace:

```
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
   at EY.EInvoiceSender.Repository.InvoiceRepository.GetClientsWantToReceiveInvoiceByPaper(IEnumerable`1 clientId) in C:\Users\Florian.Nouri\source\repos\EY.EInvoiceSender\EY.EInvoiceSender.Repository\InvoiceRepository.cs:line 67
   at EY.InvoiceSender.EmailService.SendInvoiceAndAttachments(IDictionary`2 filesToSend) in C:\Users\Florian.Nouri\source\repos\EY.EInvoiceSender\EY.InvoiceSender.EmailService\EmailService.cs:line 110
   at EY.EInvoiceSender.Service.EInvoiceSenderService.ProcessInvoicesAsync(IEnumerable`1 invoices) in C:\Users\Florian.Nouri\source\repos\EY.EInvoiceSender\EY.EInvoiceSender.Service\EInvoiceSenderService.cs:line 102
   at EY.EInvoiceSender.Service.EInvoiceSenderService.StartAsync(CancellationToken cancellationToken) in C:\Users\Florian.Nouri\source\repos\EY.EInvoiceSender\EY.EInvoiceSender.Service\EInvoiceSenderService.cs:line 53
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at EY.EInvoiceSender.Service.Program.Main(String[] args) in C:\Users\Florian.Nouri\source\repos\EY.EInvoiceSender\EY.EInvoiceSender.Service\Program.cs:line 49
ClientConnectionId:60fa8db0-52a7-4d78-a82d-6275f30f9312
```

Did someone encounter the same issue ?

PS : I wish you an happy new year 2020

**Comment by mgravell** [comment]
I see the closure, but I'm very curious as to what happened here. Was it a
local typo? You don't have to say, of course - I'm just intrigued!
