### ISSUE TITLE
Dapper Plus InsertMany throwing null reference exception

### ISSUE THREAD

**Issue by jspinella** [StackExchange/Dapper#1401]
I know this is usually a problem with the user code and not an issue with Dapper itself, but it seems to have started happening after upgrading to the latest version of Dapper.Plus (v3.0.0) and the latest version of MySql.Data (8.0.19). 

Here's the stack trace excluding the call from my repo method to BulkInsert():
`   at Z.Dapper.Plus.DapperPlusAction.Execute()
   at Z.Dapper.Plus.DapperPlusActionSet`1.DapperPlusActionSetBuilder(DapperPlusContext context, IDbConnection connection, IDbTransaction transaction, String mapperKey, DapperPlusActionKind actionKind, IEnumerable`1 items, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusActionSet`1..ctor(DapperPlusContext context, IDbConnection connection, String mapperKey, DapperPlusActionKind actionKind, IEnumerable`1 items, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusExtensions.BulkInsert[T](IDbConnection connection, String mapperKey, IEnumerable`1 items, Func`2[] selectors)
   at Z.Dapper.Plus.DapperPlusExtensions.BulkInsert[T](IDbConnection connection, IEnumerable`1 items, Func`2[] selectors)`

I get this error when attempting to bulk insert into a MySql table. I have confirmed that the column names are identical (down to the casing) between the MySql table and the C# poco. Currently I am getting this exception when attempting to InsertMany on a single record from the large number of records I was INSERTing before. Standard Dapper methods that SELECT from MySql tables are executing without issue leading up to this exception.

**Comment by mgravell** [comment]
Hi. We are not dapper plus. Dapper plus are not affiliated or associated
with the Dapper team in any way. We are not the same people. Confusing, I
know, but: blame them for that.

I suggest you ask them.

**Comment by jspinella** [comment]
No worries, I found this earlier: https://github.com/zzzprojects/Dapper-Plus but noticed there hadn't been any commits in a few months so I figured that was someone's fork. Is that the correct repo?
