### ISSUE TITLE
Failed to insert large size of string into oracle clob type.

### ISSUE THREAD

**Issue by caoyang1024** [StackExchange/Dapper#142]
When I was trying to insert a large size of string into oracle clob type, I  will see exception : Specified argument was out of the range of valid values.

**Comment by miguelerm** [comment]
I solved in my project creating a custom query parameter, someting like this:

```cs
internal class OracleClobParameter : SqlMapper.ICustomQueryParameter
{
    private readonly string value;

    public OracleClobParameter(string value)
    {
        this.value = value;
    }

    public void AddParameter(IDbCommand command, string name)
    {

        // accesing the connection in open state.
        var clob = new Oracle.DataAccess.Types.OracleClob(command.Connection as Oracle.DataAccess.Client.OracleConnection);

        // It should be Unicode oracle throws an exception when
        // the length is not even.
        var bytes = System.Text.Encoding.Unicode.GetBytes(value);
        var length = System.Text.Encoding.Unicode.GetByteCount(value);

        int pos = 0;
        int chunkSize = 1024; // Oracle does not allow large chunks.

        while (pos < length)
        {
            chunkSize = chunkSize > (length - pos) ? chunkSize = length - pos : chunkSize;
            clob.Write(bytes, pos, chunkSize);
            pos += chunkSize;
        }

        var param = new Oracle.DataAccess.Client.OracleParameter(name, Oracle.DataAccess.Client.OracleDbType.Clob);
        param.Value = clob;

        command.Parameters.Add(param);
    }
}
```

And then using this parameter in my command:

```cs
connection.Execute("INSERT INTO MESSAGES VALUES (:id, :text)", new {id = 1, text = new OracleClobParameter("my large text") });
```

It's not a real solution, but works for me, :)

I hope this helps to create a real solution in a future.

**Comment by Boggin** [comment]
+1 for @miguelerm as his solution also worked for me

**Comment by rpbeier** [comment]
Thanks @miguelerm, this worked for us too :)

**Comment by warnee** [comment]
Thanks @miguelerm this solution worked for me

**Comment by waldimen** [comment]
I am using dynamic parameters and it does not work for me:

```
    var itemParams = new DynamicParameters(doc);
    itemParams.Add("LargeText",new OracleClobParameter(doc.LargeText));

```
Any ideas how to make it work ?

**Comment by mgravell** [comment]
well... what happened? an exception (and if so: exactly what)? or was the
data truncated? not sent at all?

On 13 Dec 2017 11:53 a.m., "waldimen" <notifications@github.com> wrote:

I am using dynamic parameters and it does not work for me:

    var itemParams = new DynamicParameters(doc);
    itemParams.Add("LargeText",new OracleClobParameter(doc.LargeText));


Any ideas how to make it work ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/Dapper/issues/142#issuecomment-351369861>,
or mute the thread

**Comment by AttilaDNagy** [comment]
I have the same issue (.NET core) in March 2019.
Are they planning to solve this issue?

**Comment by MetSystem** [comment]
I have the same issue .

**Comment by diegosps** [comment]
The problem still happens on version 1.60.6 with oracle managed data access core (2.19.31).
Thankfully, @miguelerm solution still works with adjusted namespaces.

**Comment by wast** [comment]
With Dapper.Oracle this worked for me:
```
var parameters = new OracleDynamicParameters();
parameters.Add("JSONDOCUMENT", BusinessCaseSaveRequest.JsonDocument, OracleMappingType.Clob, ParameterDirection.Input);
```

**Comment by AttilaDNagy** [comment]
> 
> 
> With Dapper.Oracle this worked for me:
> 
> ```
> var parameters = new OracleDynamicParameters();
> parameters.Add("JSONDOCUMENT", saveRequest.JsonDocument, OracleMappingType.Clob, ParameterDirection.Input);
> ```

Was the parameter string in C# with more than 4000 characters?

**Comment by wast** [comment]
Worked with more than 300.000 characters.

**Comment by luoyanglihao** [comment]
I have the same issue . @mgravell

**Comment by NickCraver** [comment]
@luoyanglihao did you try the Dapper.Oracle approach above? Oracle has so many non-standard things happening w.r.t. .NET, I'm leaning towards just recommending that library and not changing Dapper core to work around the issues...since they're doing a great job of it.

**Comment by deepbluesky** [comment]
Usage of DynamicParameters worked for us. (Dapper version 2.0.90)

```
var queryParams = new DynamicParameters(new  
{  
    SYSTEMID = SystemId,  
    KEYNAME = KeyName  
});  
queryParams.Add("TOKEN", value, DbType.String, size: 65536);
_connection.Execute(UPDATE_TOKEN, queryParams);
```

**Comment by sunghwan2789** [comment]
> Usage of DynamicParameters worked for us. (Dapper version 2.0.90)
> 
> ```cs
> var queryParams = new DynamicParameters(new  
> {  
>     SYSTEMID = SystemId,  
>     KEYNAME = KeyName  
> });  
> queryParams.Add("TOKEN", value, DbType.String, size: 65536);
> _connection.Execute(UPDATE_TOKEN, queryParams);
> ```

I checked that this works in Dapper v1.8.0 too.
We can omit `size` param:
```cs
queryParams.Add("TOKEN", value, DbType.String);
```

**Comment by edobnet** [comment]
I have same question

**Comment by nkkarasu** [comment]
Same for me.

FrameWork: .Net 6.0
Dapper: 2.0.123
Oracle.ManagedDataAccess.Core: 3.21.65

**System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.** thrown if the data size exceeds 4Kb.

`System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Oracle.ManagedDataAccess.Client.OracleParameter.set_Size(Int32 value)
   at ParamInfoebf64429-6c5c-4a94-9646-cd34dfc8e77f(IDbCommand , Object )
   at Dapper.CommandDefinition.SetupCommand(IDbConnection cnn, Action`2 paramReader)
   at Dapper.SqlMapper.TrySetupAsyncCommand(CommandDefinition command, IDbConnection cnn, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param)`

Also @sunghwan2789's solution worked for me.

**Comment by MiddleKerb** [comment]
> Usage of DynamicParameters worked for us. (Dapper version 2.0.90)
> 
> ```
> var queryParams = new DynamicParameters(new  
> {  
>     SYSTEMID = SystemId,  
>     KEYNAME = KeyName  
> });  
> queryParams.Add("TOKEN", value, DbType.String, size: 65536);
> _connection.Execute(UPDATE_TOKEN, queryParams);
> ```

Thanks, this solution worked for me in Dapper 2.0.123 with .Net 6.0

**Comment by fsbflavio** [comment]
In fact using DynamicParameters solves the issue.

But what about solving it for anonymous parameters as well? I make use of it frequently, and unfortunately, using DynamicParameters does not allow me to retrieve the parameter name using the 'nameof' operator.

here is a sample:
```csharp
public void SaveLog(Exception ex, string userId)
{
    var parameters = new
    {
        user = userId,
        message = ex.Message,
        stacktrace = ex.ToString(), //clob bigger than 4000
    };

    var sql = $@"INSERT INTO LOG (
                        ID_LOG, 
                        ID_USUARIO, 
                        STACKTRACE
                  ) VALUES (
                        SQ_ID_LOG.NEXTVAL, 
                        :{nameof(parameters.user)}, 
                        :{nameof(parameters.message)}, 
                        :{nameof(parameters.stacktrace)})";

    db.Execute(sql, parameters);
}
```

**Comment by Drwillard** [comment]
Update for 2024 - .NET 6/8, Dapper 2.1.x - @miguelerm solution is working for me with minimal modification -

```
using Dapper;
using System.Data;

namespace MyNamespace;

internal class OracleClobParameter : SqlMapper.ICustomQueryParameter
{
    private readonly string value;

    public OracleClobParameter(string value)
    {
        this.value = value;
    }

    public void AddParameter(IDbCommand command, string name)
    {

        // accesing the connection in open state.
        var clob = new Oracle.ManagedDataAccess.Types.OracleClob(command.Connection as Oracle.ManagedDataAccess.Client.OracleConnection);


        // It should be Unicode oracle throws an exception when
        // the length is not even.
        var bytes = System.Text.Encoding.Unicode.GetBytes(value);
        var length = System.Text.Encoding.Unicode.GetByteCount(value);

        int pos = 0;
        int chunkSize = 1024; // Oracle does not allow large chunks.

        while (pos < length)
        {
            chunkSize = chunkSize > (length - pos) ? chunkSize = length - pos : chunkSize;
            clob.Write(bytes, pos, chunkSize);
            pos += chunkSize;
        }

        var param = new Oracle.ManagedDataAccess.Client.OracleParameter(name, Oracle.ManagedDataAccess.Client.OracleDbType.Clob);
        param.Value = clob;

        command.Parameters.Add(param);
    }
}```
