### ISSUE TITLE
Parameter bind error for oracle data type "INTERVAL DAY TO SECOND"

### ISSUE THREAD

**Issue by victor-wiki** [StackExchange/Dapper#1426]
I use Oracle.ManagedDataAccess.Client to bind "TimeSpan" to Oracle "INTERVAL DAY TO SECOND":
```
TimeSpan obj = TimeSpan.Parse("17:00:00");
Dictionary<string, object> parameters = new Dictionary<string, object>(); 
CommandDefinition cmd = new CommandDefinition("INSERT INTO TEST(TS) VALUES(:V)", parameters);
connection.Execute(cmd);
```
it throws:
```
Invalid parameter binding
Parameter name: ParameterName
   at OracleInternal.ServiceObjects.OracleParameterImpl.SetTimeStampInBytes(Object bindValue, Byte[]& timeStampByteArray)
   at OracleInternal.ServiceObjects.OracleParameterImpl.SetTimeStampInBytes(Object bindValue)
```
But, i use the following code, it's ok
 ```
TimeSpan obj = TimeSpan.Parse("17:00:00");
CommandDefinition cmd = new CommandDefinition("INSERT INTO TEST(TS) VALUES(:V)", new {V=obj});
connection.Execute(cmd);
```

**Comment by NickCraver** [comment]
Gotcha - thanks for the example! In short, we expect an object, or alternatively a `new DynamicParameters()` as the collection - a dictionary is not expected here :)

**Comment by victor-wiki** [comment]
i see, thanks for your reply.
