### ISSUE TITLE
'System.Data.ProviderBase.DbConnectionClosedConnecting' to type 'System.Data.SqlClient.SqlInternalConnectionTds'.

### ISSUE THREAD

**Issue by maobiwen** [StackExchange/Dapper#1568]
I got two errors
=========one error============
`fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM44F9PHNH0J", Request id "0HM44F9PHNH0J:00000001": An unhandled exception was thrown by the application.
System.InvalidCastException: Unable to cast object of type 'System.Data.ProviderBase.DbConnectionClosedConnecting' to type 'System.Data.SqlClient.SqlInternalConnectionTds'.
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1079
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 721
   at DapperBase.GetList[T](String sqlString, Object param, Nullable`1 commandType, Nullable`1 commandTimeout) in D:\www\youluOpenApi\YOP.Data\DapperBase.cs:line 64
   at DapperBase.GetList[T](String sqlString, Object param) in D:\www\youluOpenApi\YOP.Data\DapperBase.cs:line 87
   at YOP.Data.Repository.BookRepository.GetBookByBookId(Int32 bookId) in D:\www\youluOpenApi\YOP.Data\Repository\BookRepository.cs:line 38
   at YOP.Services.BookService.GetBook(Int32 bookId) in D:\www\youluOpenApi\YOP.Services\Book\BookService.cs:line 33
   at shopOpenApi.Factories.ShopApiResponseFactory.PrepareShopItemsOnsaleGetResponse(List`1 shpStores) in D:\www\youluOpenApi\shopOpenApi\Factories\ShopApiResponseFactory.cs:line 48`

================two error=============
```
`System.InvalidOperationException: The connection was not closed. The connection's current state is connecting.
   at System.Data.ProviderBase.DbConnectionClosedConnecting.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1079
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 721
   at DapperBase.GetList[T](String sqlString, Object param, Nullable`1 commandType, Nullable`1 commandTimeout) in D:\www\youluOpenApi\YOP.Data\DapperBase.cs:line 64
   at DapperBase.GetList[T](String sqlString, Object param) in D:\www\youluOpenApi\YOP.Data\DapperBase.cs:line 87
   at YOP.Data.Repository.BookRepository.GetBookByBookId(Int32 bookId) in D:\www\youluOpenApi\YOP.Data\Repository\BookRepository.cs:line 38
   at YOP.Services.BookService.GetBook(Int32 bookId) in D:\www\youluOpenApi\YOP.Services\Book\BookService.cs:line 33
   at shopOpenApi.Factories.ShopApiResponseFactory.PrepareShopItemsOnsaleGetResponse(List`1 shpStores) in D:\www\youluOpenApi\shopOpenApi\Factories\ShopApiResponseFactory.cs:line 48`
```
============================
this is my main code

In StartUp.cs   ConfigureServices(IServiceCollection services)
        
  services.AddSingleton<IConfiguration>(Configuration);
            services.AddTransient<IDapper, DapperBase>();

            services.AddTransient<IShopApiResponseFactory, ShopApiResponseFactory>();
            services.AddTransient<IShopManagerSystemRepository, ShopManagerSystemRepository>();
            services.AddTransient<IBookService, BookService>();
            services.AddTransient<IOrderService, OrderService>();
            
            services.AddTransient<IAreaService, AreaService>();

            services.AddTransient<IBookRepository, BookRepository>();
            services.AddTransient<IAreaRepository, AreaRepository>();
            services.AddTransient<IShopInfoRepository, ShopInfoRepository>();
            services.AddTransient<IShpOrderRepository, ShpOrderRepository>();
            services.AddTransient<IShpOrderApiResponseFactory, ShpOrderApiResponseFactory>();
            services.AddTransient<IItemRepository, ItemRepository>();

BookService.cs
   private readonly IBookRepository _bookRepository;
        private readonly IDistributedCache _cache;
        public BookService(IBookRepository bookRepository, IDistributedCache cache)
        {
            _bookRepository = bookRepository;
            _cache = cache;
        }

BookRepository.cs

 private IConfiguration _configuration;
        private DapperFactory _factory;
        private IDapper _dapper;
        public BookRepository(IConfiguration configuration)
        {
            _configuration = configuration;
            _factory = DapperFactory.GetInstance(configuration);
            _dapper = _factory.GetDapper();

        }

public IDapper GetDapper()
    {
        if (null == _dapper)
        {
            var connectionString = string.Empty;
            var connectionTypeString = string.Empty;
            ConnectionType connType = ConnectionType.SqlServer;

            if (null != _configuration.GetSection(CONNECTION_STRING) && null != _configuration.GetSection(CONNECTION_STRING).GetSection(STUDENT_CONNECTION_STRING))
            {
                connectionString = _configuration.GetSection(CONNECTION_STRING).GetSection(STUDENT_CONNECTION_STRING).Value;
            }
            if (null != _configuration.GetSection(CONNECTION_TYPE))
            {
                connectionTypeString = _configuration.GetSection(CONNECTION_TYPE).Value;
            }
            if (!string.IsNullOrWhiteSpace(connectionTypeString))
            {
                connType = connectionTypeString.ConvertFromString<ConnectionType>();
            }
            //connectionString = "Data Source=106.225.216.211;Initial Catalog=data_youlu3;Persist Security Info=True;User ID=sa;Password=.netyoulu5_1_900.800";
            _dapper = new DapperBase(connType, connectionString);
        }

        return _dapper;
    }

    public Book GetBookByBookId(int bookId)
        {
            var list = _dapper.GetList<Book>(Book_SELECT_byId_SQL_STRING, new { bookId = bookId });
            if (null != list && list.Count > 0)
            {
                return list.FirstOrDefault();
            }
            else { return null; }
        }

 public List<T> GetList<T>(string sqlString, object param)
    {
        if (null == param)
        {
            return GetList<T>(sqlString);
        }
        else
        {
            return GetList<T>(sqlString, param, CommandType.Text);
        }
    }

  public List<T> GetList<T>(string sqlString, object param = null, CommandType? commandType = CommandType.Text, int? commandTimeout = 180)
    {
        var list = new List<T>();

        using (var db = IDbConnection as DbConnection)
        {
            IEnumerable<T> ts = null;
            if (null == param)
            {
                ts = db.Query<T>(sqlString, null, null, true, commandTimeout, commandType);
            }
            else
            {
                ts = db.Query<T>(sqlString, param, null, true, commandTimeout, commandType);
            }
            if (null != ts)
            {
                list = ts.AsList();
            }
        }
        return list;
    }

Please help !if request Single-Threaded ，it run good ,if request Multi-threading ,it will disapper errors and the time out ,help
My English is poor !sorry

**Comment by maobiwen** [comment]
it is my wrong 。
