### ISSUE TITLE
Text column cannot be mapped to nullable enum

### ISSUE THREAD

**Issue by SethTales** [StackExchange/Dapper#1653]
I have a table with a text column that allows nulls. This text column holds the string representation of an enum:

```
public enum Status
    {
        NotConnected,
        Connected
    }
```

When making updates or inserts into this table, it works just fine because I can use the ?. null-conditional operator which seems to make Dapper happy. However, when doing reads I get an error:

```
System.Data.DataException: Error parsing column 3 (status= - String)
 ---> System.ArgumentException: Must specify valid information for parsing in the string. (Parameter 'value')
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Deserialize2098d38f-668f-47dd-8226-fb67d62b44fc(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3665
   at Deserialize2098d38f-668f-47dd-8226-fb67d62b44fc(IDataReader )
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command)
```

presumably because dapper does not know what to do if the column is null. Is there a way to get Dapper to do the right thing, maybe through custom type handlers or mappers?

**Comment by NickCraver** [comment]
Can you show your query code here? Specifically, are you querying it as `Status` or `Status?` - an example usage would help advise here.

**Comment by khairuzzaman** [comment]
I don't know which version you used. But the current version is working as expected. I have write a test case and the test case pass with null value


`private enum EnumParam : short
{
    None = 0,
    A = 1,
    B = 2
}

[Fact]
public void TestEnumParamsWithNullableString()
{
    const string a = "1";
    const string b = "2";
    const string c = null;
    var obj = connection.Query<EnumParamObject>("select @a as A, @b as B, @c as C",
        new { a, b, c }).Single();
    Assert.Equal(EnumParam.A, obj.A);
    Assert.Equal(EnumParam.B, obj.B);
    Assert.Null(obj.C);
}`

![image](https://user-images.githubusercontent.com/10438018/133459653-4d0bbe8a-aa65-46b8-adda-bd00a391dca5.png)
