### ISSUE TITLE
Null ref exception after Dapper.SqlMapper.GetColumnHash with Sqlite on .NET Core 2.0

### ISSUE THREAD

**Issue by cartermp** [StackExchange/Dapper#848]
**Repro project:** 
[Test.zip](https://github.com/StackExchange/Dapper/files/1308837/Test.zip)

**Steps:**
1. Open the project and `dotnet run` it.
2. Send a POST with the following JSON data:

```json
{ "Name": "Coquette2", "Cuisine": "French", "Latitude":47.625274, "Longitude":-122.518320, "VegetarianOptions": true, "VeganOptions": false }
```

**Results:**

Row is successfully added to the Sqlite DB, but the server has an uncaught null ref exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SQLitePCL.raw.sqlite3_column_count(sqlite3_stmt stmt)
   at Microsoft.Data.Sqlite.SqliteDataReader.get_FieldCount()
   at Dapper.SqlMapper.GetColumnHash(IDataReader reader, Int32 startBound, Int32 length)
   at Dapper.SqlMapper.<QueryImpl>d__124`1.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at DataAccess.DapperFSharp.dapperQuery[Result](String query, SqliteConnection connection) in /Users/phillip/scratch/bar/DataAccess.fs:line 13
   at DataAccess.LunchAccess.addLunch(LunchSpot lunchSpot) in /Users/phillip/scratch/bar/DataAccess.fs:line 28
   at bar.App.handleAddLunch@33-1.Invoke(LunchSpot _arg1) in /Users/phillip/scratch/bar/Program.fs:line 33
   at Giraffe.TaskBuilder.run[a](FSharpFunc`2 firstStep)
```

I initially thought that this was clearly some problem either in SQLitePCL or MS.Data.Sqlite, but everything works if I use MS.Data.Sqlite directly.  The code in both of those projects for `FieldCount` and `sqlite3_column_count` wasn't doing anything fancy, either.  Just calling down into Sqlite itself I think.

**Relevant info:**

* .NET Core
* Sqlite
* macOS 10.12.6

The code in question is pretty simple.  I don't think I'm doing something "clever" here, though I could be wrong about that.

```fsharp
module DapperFSharp =
    let dapperQuery<'Result> (query: string) (connection: SqliteConnection) =
        connection.Query<'Result>(query)

open DapperFSharp

module LunchAccess =
    let private connString = "Filename=" + Path.Combine(Directory.GetCurrentDirectory(), "Sample.db")

    let addLunch (lunchSpot: LunchSpot) =
        let query = 
            sprintf 
                "insert into LunchSpots (Name, Latitude, Longitude, Cuisine, VegetarianOptions, VeganOptions) values (\"%s\", %f, %f, \"%s\", %d, %d)" lunchSpot.Name lunchSpot.Latitude lunchSpot.Longitude lunchSpot.Cuisine (if lunchSpot.VegetarianOptions then 1 else 0) (if lunchSpot.VeganOptions then 1 else 0)

        use conn = new SqliteConnection(connString)
        conn.Open()
        
        dapperQuery query conn
        |> ignore
```

If I use Microsoft.Data.Sqlite directly, everything works.

```fsharp
    let addLunchWithSystemDataSqliteDirectly (lunchSpot: LunchSpot) =
        use conn = new SqliteConnection(connString)
        conn.Open()
        
        use txn: SqliteTransaction = conn.BeginTransaction()

        let cmd = conn.CreateCommand()
        cmd.Transaction <- txn
        cmd.CommandText <- "insert into LunchSpots (Name, Latitude, Longitude, Cuisine, VegetarianOptions, VeganOptions) values ( $Name , $Latitude, $Longitude, $Cuisine, $VegetarianOptions, $VeganOptions)"

        cmd.Parameters.AddWithValue("$Name", lunchSpot.Name) |> ignore
        cmd.Parameters.AddWithValue("$Latitude", lunchSpot.Latitude) |> ignore
        cmd.Parameters.AddWithValue("$Longitude", lunchSpot.Longitude) |> ignore
        cmd.Parameters.AddWithValue("$Cuisine", lunchSpot.Cuisine) |> ignore
        cmd.Parameters.AddWithValue("$VegetarianOptions", lunchSpot.VegetarianOptions) |> ignore
        cmd.Parameters.AddWithValue("$VeganOptions", lunchSpot.VeganOptions) |> ignore

        cmd.ExecuteNonQuery() |> ignore

        txn.Commit()
```

Happy to move this elsewhere.  I'm honestly not sure where the issue lies, so I figured I'd start at the top of the stack.

**Comment by NickCraver** [comment]
Since this is a null ref in the Sqlite code, issue should be filed over at https://github.com/aspnet/Microsoft.Data.Sqlite - exactly what you have is an awesome start :) Thanks for the report and asking where this goes! If we need to make changes, poke here and I'll re-open.
